name: real_time_location
description: A Real time location service.
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  firebase_core: ^2.30.0
  firebase_database: ^10.5.2
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  location: ^6.0.1
#  location: ^3.2.1
#  geocoding: ^1.0.5
#  firebase_database: ^6.0.0
#  dio: ^3.0.10

dev_dependencies:
  firebase_database_mocks: ^0.6.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  very_good_analysis: ^5.1.0
#  pedantic: ^1.9.0
#  mockito: ^4.1.3
#  firebase_database_mocks: ^0.1.0+3

publish_to: none